import lmstudio as lms

sector = {
	"art": [
		"What is your favorite artistic style or genre, and why do you enjoy it?",
		"How important do you think artistic expression is in our daily lives?",
		"Do you believe that art can influence society's values and attitudes? Why or why not?",
		"What role does creativity play in the development of a successful artist?",
		"In your opinion, what makes a piece of artwork impactful or memorable?",
		"How has art evolved over time, and do you think it will continue to evolve in the future?",
		"Are there any particular artists or movements that have had a significant impact on your appreciation of art?",
		"What role does art play in our understanding of history?",
		"How important is cultural background when evaluating and appreciating art?",
		"Do you think art has the power to bring people together, or does it often create divisions based on personal interpretation?",
	],
	"business_money": [
		"What do you think about the impact of technology on traditional businesses?",
		"How important is financial literacy in today's economic landscape?",
		"What are your thoughts on the role of government in regulating financial markets?",
		"In your opinion, what qualities make a successful entrepreneur?",
		"How do you feel about income inequality and its impact on society?",
		"What are your thoughts on cryptocurrencies as an investment or form of currency?",
		"Do you believe that education plays a significant role in one's financial success?",
		"What are your views on the ethics of corporate greed and how it affects businesses?",
		"How do you think the gig economy has impacted traditional employment models?",
		"In your opinion, what measures should be taken to protect consumers from predatory lending practices?",
	],
	"communication_personality": [
		"How do you feel about effective communication in the workplace? Is it essential, or can it be overlooked?",
		"What are your thoughts on the role of empathy in interpersonal communication?",
		"Do you think that body language is as important as verbal communication in conveying messages? Why or why not?",
		"How would you rate your ability to understand and adapt to different personality types during interactions?",
		"In your opinion, what are the most effective ways to overcome communication barriers (language, cultural, etc.) when dealing with people from diverse backgrounds?",
		"What are your thoughts on the concept of active listening in communication? Do you believe it is an essential skill to have? Why or why not?",
		"How do you feel about the impact of technology on communication and personal relationships? Are there any pros or cons?",
		"Do you think that communication and personality traits can influence each other, or are they separate entities? Explain your stance.",
		"What is your opinion on how communication plays a role in conflict resolution within relationships? Does it have the power to resolve disputes, or does it worsen them?",
		"How would you rate the importance of non-verbal cues like eye contact, facial expressions, and gestures in effective communication?",
	],
	"crime_punishment": [
		"What do you think is the most effective way to deter crime?",
		"Do you believe that the death penalty should be allowed in certain cases? Why or why not?",
		"How important is rehabilitation versus retribution when dealing with criminals?",
		"Should there be a distinction between harsh punishments for minor offenses and more lenient ones for serious crimes?",
		"What do you think about the use of surveillance cameras to prevent crime? Are they effective?",
		"Do you feel that mandatory drug testing should apply to all individuals, especially those in positions of authority or high-risk jobs? Why or why not?",
		"Should there be harsher punishments for crimes against children?",
		"What is your opinion on the privatization of prisons? Are they more effective than publicly run facilities?",
		"Do you think that the war on drugs has been successful in reducing crime rates? Why or why not?",
	],
	"education": [
		"What do you think is the most important skill for success in today's job market?",
		"Should standardized testing be abolished in favor of a more holistic approach to assessing student abilities?",
		"Do you believe that online education can ever fully replace traditional classroom learning? Why or why not?",
		"What are your thoughts on the concept of homeschooling versus traditional public/private schooling?",
		"How do you feel about incorporating technology in the classroom, and what are your views on its impact on student engagement and learning outcomes?",
		"In your opinion, what is the best way to address the issue of teacher shortages in underfunded schools or districts?",
		"What role should parents play in their children's education, and do you think they should be more involved than they currently are?",
		"Should school curriculum be standardized across all states/countries or left up to individual educational institutions for flexibility? Why?",
		"How do you feel about the use of extracurricular activities in schools, and what benefits or drawbacks do you see associated with them?",
		"What are your thoughts on the current state of education funding and how it impacts students' access to resources and opportunities?",
	],
	"environment": [
		"What do you think is the most important factor in protecting our planet's health?",
		"Should humans be allowed to alter natural landscapes for urban development and agriculture? Why or why not?",
		"How can we balance economic growth with environmental protection, ensuring that both thrive?",
		"Is it ethical to use animals for scientific research, considering the potential harm it may cause?",
		"What role should individuals play in protecting the environment, beyond recycling and reducing waste?",
		"Do you believe the concept of sustainability is achievable, or are we too dependent on resources that cannot be replenished?",
		"How important do you think renewable energy sources like solar and wind power are for our future? Why?",
		"Should there be more regulation on the use of pesticides in agriculture to protect both human health and ecosystems?",
		"What can governments do to encourage citizens to participate in environmental conservation efforts?",
		"How significant is climate change, and what should we do about it?",
		"Do you think technology, like electric cars or smart grids, is a sufficient solution for reducing carbon emissions? Why or why not?",
		"What kind of wildlife and wilderness areas are most important to protect? Why?",
	],
	"families_children": [
		"How important is it for parents to set boundaries for their children?",
		"What do you think are the most effective ways to discipline children?",
		"Do you believe that all children should have access to education regardless of their family's financial status?",
		"Should parents be more involved in their children's social media use?",
		"How much influence does a parent's relationship with their child impact their overall happiness?",
		"What role do extended family members play in the upbringing of a child, and how can they contribute to their development?",
		"Do you think it's appropriate for parents to allow children to use electronic devices during meal times?",
		"How important is it for parents to prioritize spending time with their children on weekends and holidays?",
		"Should parents be more involved in their child's career choices or should they let them make those decisions independently?",
		"What do you think about the role of technology in family communication and how it affects face-to-face interactions within families?",
	],
	"food_diet": [
		"Do you prefer organic or conventional produce?",
		"What is your favorite type of cuisine?",
		"Are vegetarian or vegan diets better for the environment?",
		"Should school lunches include more plant-based options?",
		"How important is it to eat locally sourced foods?",
		"Do you believe in following a specific diet plan, such as keto, Mediterranean, or gluten-free?",
		"What role does food play in your cultural traditions?",
		"Are you concerned about the use of pesticides and herbicides in farming?",
		"How often do you eat fast food?",
		"Do you think cooking at home is more beneficial than eating out or ordering delivery?",
	],
	"government": [
		"What do you think should be the priorities of the government in terms of infrastructure development?",
		"Do you believe that the current taxation system is fair and effective?",
		"What measures do you suggest for reducing corruption within the government institutions?",
		"Should the government have a more active role in regulating the media, or should it be left to private entities?",
		"In your opinion, how important is transparency in the government's decision-making process?",
		"What changes would you like to see in the public education system under government administration?",
		"How do you feel about the current immigration policies of your country?",
		"Do you think there should be a higher focus on women's rights and gender equality within the government framework?",
		"What do you believe are the most pressing issues in healthcare delivery, and how would you want the government to address them?",
		"How important is it for the government to provide free or subsidized public transportation systems for its citizens?",
	],
	"health": [
		"What do you think is the most important factor in maintaining good health?"
		"Should access to healthcare be considered a basic human right or a privilege?"
		"How much time do you spend on physical activity each week, and do you feel it's enough?"
		"Do you believe that a plant-based diet is better for your health than one that includes meat and dairy products?"
		"What are some of the biggest challenges in promoting public health?"
		"How important do you think mental health is compared to physical health, and why?"
		"Do you think genetically modified foods should be labeled as such for consumer protection?"
		"What role do you believe traditional medicine and alternative therapies play in modern healthcare?"
		"How often do you engage with your friends or family about their health? And why is it important to do so?"
		"Do you think the cost of healthcare should be a shared responsibility between the government, employers, and individuals?"
	],
	"housing_buildings_urban_planning": [
		"What do you think is the most important factor in ensuring affordable housing for all residents of a city?",
		"How can cities strike a balance between preserving historic buildings and encouraging new construction to meet growing population needs?",
		"What are your thoughts on the implementation of green building standards in urban developments?",
		"Do you believe that increasing the number of affordable housing units should be a priority for local governments, or is it more important to focus on economic development?",
		"How can cities ensure that new developments contribute positively to the community's overall aesthetics and character while also meeting functional requirements?",
		"What do you think are the most effective ways to encourage developers to invest in sustainable building practices?",
		"Should urban planning policies prioritize mixed-use developments or single-use zoning, and why?",
		"How can cities ensure that new construction projects consider the needs of both current residents and future generations?",
		"What strategies do you think would be most effective for revitalizing blighted neighborhoods while maintaining community identity?",
		"In what ways can urban planning encourage a sense of belonging among city residents, particularly in densely populated areas?",
	],
	"language": [
		"What is your favorite language to learn, and why do you enjoy it?",
		"Do you think English should be the official language of the world, considering its global influence?",
		"How important is it for people to preserve their native languages in a multilingual society like ours?",
		"Should there be a universal translation app that can translate any language into another instantly, or do you prefer human translators?",
		"What are your thoughts on bilingual education and its impact on students' cognitive skills and academic performance?",
		"How important is it for travelers to learn a few basic phrases in the local language of their destination country?",
		"Is it better to teach languages from a young age or wait until adulthood, considering the ease of learning new languages at different stages?",
		"What are your views on the use of artificial intelligence in translating and interpreting languages, and its potential impact on traditional linguistics?",
		"Should governments invest more resources in promoting language education and preserving endangered languages to maintain cultural diversity?",
		"How important is it for people to know a few basic phrases in other languages while traveling internationally, considering the globalization trend?",
	],
	"leisure": [
		"What do you enjoy doing in your free time, and why is it important for you?",
		"Do you prefer spending time indoors or outdoors during your leisure time? Why?",
		"Which hobbies have had the most positive impact on your life, and how did they benefit you?",
		"How do you think technology has changed the way we spend our leisure time, both positively and negatively?",
		"In your opinion, what activities should people prioritize to maintain a healthy balance between work and leisure time?",
		"Do you believe that it's essential for everyone to have a hobby or engage in some form of recreational activity? Why or why not?",
		"Have you ever tried a new leisure activity, and what did you learn from the experience?",
		"How do you think people can make more time for their leisure activities without feeling guilty about neglecting work responsibilities?",
		"What role does family play in shaping someone's leisure interests and activities?",
		"Do you think it's important to travel or explore new places as part of your leisure time, and why?",
	],
	"media_advertising": [
		"What do you think about the increasing use of AI and machine learning in media targeting and advertising strategies? Do you believe it enhances user experience or raises concerns about privacy?",
		"How important is authenticity in influencer marketing, and what role does transparency play in building trust with consumers?",
		"In your opinion, which social media platform has the most effective advertising strategy for brands? Why do you think so?",
		"What are your thoughts on the use of personal data in targeted advertising? Do you think it's necessary for a more tailored user experience or an invasion of privacy?",
		"How do you see the future of traditional media (television, newspapers) in the digital age? Will they continue to be relevant, or will they fade away with the rise of online platforms?",
		"What is your take on the role of advertising in shaping public opinion and influencing consumer behavior? Do you think it has a significant impact on society?",
		"How do you feel about the current state of media regulation, particularly when it comes to transparency and accountability for advertisers?",
		"In your view, which traditional advertising methods (e.g., print ads, billboards) are still effective in today's digital world, and why?",
		"What are your thoughts on the balance between personalization and privacy in advertising? Do you think there should be stricter regulations to protect user data?",
		"How do you see the future of media ownership and distribution in a landscape where technology is constantly evolving? Will traditional media companies adapt, or will new players emerge in the market?",
	],
	"reading": [
		"What is your favorite book and why do you enjoy it so much?",
		"Do you prefer reading fiction or non-fiction books, and why?",
		"Have you ever read a book that completely changed your perspective on something? If yes, what was it and how did it change your viewpoint?",
		"What is the best piece of advice you've received from a book and have you tried applying it in your life?",
		"Are you more inclined to read for entertainment or for educational purposes, and why?",
		"What is your opinion on e-books versus traditional books? Which do you prefer and why?",
		"Have you ever found that reading helps you understand different cultures better? If yes, can you share an example?",
		"Do you believe that reading can influence your decision-making process or behavior? How so?",
		"What is the most unusual book you've read, and how did it differ from what you usually read?",
		"Lastly, have you ever had a debate with someone about their interpretation of a certain book? If yes, what was it and how did you handle it?",
	],
	"society": [
		"What do you think about the growing trend of remote work and its impact on traditional office culture?",
		"Do you believe that social media platforms should be held responsible for the spread of misinformation, hate speech, and cyberbullying online? Why or why not?",
		"How important is it to have diversity in leadership roles within corporations and government agencies?",
		"Should mental health be a priority when making decisions regarding public policy, like healthcare reforms or education funding? Explain your reasoning.",
		"What are your views on the role of social media platforms in promoting political discourse and civic engagement among citizens?",
		"How important is it for governments to invest in infrastructure projects that promote environmental sustainability? Why do you think this should be a priority?",
		"Should religious beliefs be considered when making decisions about public policies, like laws regarding marriage equality or reproductive rights? Explain your position on this issue.",
		"What are your thoughts on the increasing trend of individualism in modern society and its potential impact on community cohesion and social support systems?",
		"Do you think that mandatory civic education should be part of school curriculums to help students develop critical thinking skills related to current events, politics, and societal issues?",
		"What are your views on the importance of personal responsibility versus collective action in addressing various social problems within society today?",
	],
	"space_exploration": [
		"What are the most exciting discoveries that have been made through space exploration?",
		"Do you think humans should prioritize sending astronauts to Mars or focus more on exploring other planets in our solar system? Why?",
		"In what ways do you believe space exploration has influenced human society and culture?",
		"How do you feel about the cost of space exploration missions, considering they are often funded by taxpayers' money?",
		"What ethical concerns arise with regards to sending humans to other planets, such as potential harm to indigenous life forms or the psychological impact on astronauts?",
		"Should private companies be allowed to play a larger role in space exploration and commercialization of space? Why or why not?",
		"How do you think space exploration has affected our understanding of Earth and its place in the universe?",
		"What are some potential benefits that could come from further exploring the outer reaches of our solar system, such as new energy sources or advanced technologies?",
		"In your opinion, what is the greatest challenge facing space agencies today, and how can it be addressed?",
		"Do you think there will ever come a time when humans will no longer need to rely on Earth for resources and instead establish settlements on other planets?",
	],
	"sports_exercise": [
		"What do you think is the most important aspect of a successful sports team, individual performance or teamwork? Why?",
		"Do you believe in the saying \"No pain, no gain\"? Why or why not?",
		"Which sport do you think requires more skill and talent to play: football (soccer) or basketball? Explain your answer.",
		"What is your opinion on professional sports athletes' salaries compared to those of other professions?",
		"Do you think physical education should be a mandatory subject in school curriculums? Why or why not?",
		"Which sport do you find the most enjoyable, and why?",
		"What role does exercise play in maintaining good mental health?",
		"How important is sportsmanship in competitive sports, and can it be improved with training or education?",
		"Should professional athletes have a higher level of responsibility to influence social issues compared to other professions? Why or why not?",
		"What is your view on the use of performance-enhancing drugs in sports, such as steroids or other supplements?",
	],
	"technology": [
		"What do you think about the impact of artificial intelligence on society and the job market?",
		"Should governments be responsible for regulating social media platforms, or should there be a balance between free speech and protecting users from harmful content?",
		"Do you believe in the benefits of virtual reality technology, or do you think it poses more risks than advantages?",
		"What are your thoughts on the future of autonomous vehicles and their potential impact on transportation systems?",
		"Should online privacy be considered a fundamental right in the digital age, or should there be measures to protect sensitive information from being exploited?",
		"How do you feel about the influence of technology on human relationships and social interactions?",
		"What are your opinions on the use of biometric data for identification purposes, considering both its benefits and potential risks?",
		"Do you think that advancements in genetic engineering have the potential to positively impact human health or raise ethical concerns?",
		"Should governments invest more resources into developing 5G infrastructure, or do you believe other sectors require greater funding?",
		"How do you see technology shaping the future of education and learning experiences for students worldwide?",
	],
	"tourism and travel": [
		"Do you prefer exploring well-known tourist destinations or discovering off-the-beaten-path locations during your travels? Why?",
		"How important is it for tourists to respect local cultures and traditions when visiting new places? Can you give some examples of how this can be done?",
		"What role do you think technology plays in modern tourism, and do you believe it has a positive or negative impact on the travel experience? Provide reasons for your answer.",
		"As an eco-conscious traveler, what steps would you take to ensure that your trips have minimal impact on the environment and local communities?",
		"What is your opinion on the ethics of responsible tourism, such as volunteering for conservation projects abroad versus simply donating money to charities at home?",
		"How important is it for tourists to try local cuisine when traveling? Can you think of any examples where food has played a significant role in your travel experiences?",
		"What are some ways that tourism can contribute to the economic development of a country or region, and do you believe this is always beneficial?",
		"How do you feel about the impact of mass tourism on popular destinations like Venice or Machu Picchu? Do you think there should be limitations on the number of tourists visiting these places? Why or why not?",
		"What is your opinion on the use of online travel platforms, such as Airbnb and Booking.com, versus staying in traditional hotels or guesthouses when traveling? Are there any ethical concerns you have with this trend?",
		"Finally, what advice would you give to fellow travelers about how they should approach tourism in order to maximize their positive impact on the destinations they visit and the people they encounter?",
	],
	"transport": [
		"What do you think about the impact of electric cars on reducing carbon emissions from transportation?",
		"Should cities prioritize public transit over personal vehicles in urban planning?",
		"Do you believe high-speed rail is a viable alternative to air travel for long-distance journeys, or does it pose significant challenges?",
		"What are your thoughts on the role of autonomous vehicles in future transportation systems and their potential impact on road safety?",
		"How important do you think investing in infrastructure development is for improving overall transport efficiency?",
		"Do you consider bike-sharing programs to be a positive initiative that encourages physical activity while reducing congestion in cities?",
		"What are your views on the role of ride-hailing services like Uber and Lyft, and do you think they have positively or negatively affected traditional taxi industries?",
		"Should governments focus more on improving pedestrian walkability by enhancing sidewalks and crosswalks rather than solely investing in cars?",
		"How significant is the issue of traffic congestion for daily commuters, and what solutions do you support to alleviate this problem?",
		"What are your views on whether airlines should be regulated more heavily or have greater deregulation in terms of pricing and service standards?",
	],
	"work": [
		"Do you think working from home is as effective as working in an office environment?",
		"What are the most important qualities a leader should have?",
		"Should companies prioritize employee well-being or productivity when making decisions?",
		"How can managers effectively motivate their employees?",
		"Is there a correlation between job satisfaction and overall happiness?",
		"Do you believe that work-life balance is achievable in today's fast-paced society?",
		"What role does technology play in modern workplaces?",
		"Are traditional performance evaluations still relevant in the current job market?",
		"How can companies encourage diversity and inclusion within their workforce?",
		"Should employees be compensated for their personal achievements or should compensation solely come from their employer?",
	],
}

# llm = lms.llm("h2o-danube3-4b-chat")
llm = lms.llm("mistral-nemo-instruct-2407")

for n, questions in sector.items():
	with open(n + '.txt', 'w') as f:
		pass
	for q in questions:
		for _ in range(10):
			prediction = llm.respond_stream("Write long paragraphs in your response. " + q)

			with open(n + '.txt', 'a') as f:
				for token in prediction:
					print(token.content, end="", flush=True)
					f.write(token.content)
				f.write("\n\n\n")
